# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 01:31
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import sys_base.hsm.model


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                (
                    'amount',
                    models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('luna_fee',
                 models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('total', models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('txid', models.CharField(db_index=True, max_length=128)),
                ('send_gas',
                 models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('hsm_sig', models.BinaryField(null=True)),
            ],
            bases=(sys_base.hsm.model.SecureModel, models.Model),
        ),
        migrations.CreateModel(
            name='JournalOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                (
                    'amount',
                    models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('luna_fee',
                 models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('total', models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('dest_address', models.CharField(db_index=True, max_length=64)),
                ('txid', models.CharField(db_index=True, max_length=128)),
                ('send_gas',
                 models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('hsm_sig', models.BinaryField(null=True)),
            ],
            bases=(sys_base.hsm.model.SecureModel, models.Model),
        ),
        migrations.CreateModel(
            name='JournalUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                (
                    'amount',
                    models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('luna_fee',
                 models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('total', models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('hsm_sig', models.BinaryField(null=True)),
            ],
            bases=(sys_base.hsm.model.SecureModel, models.Model),
        ),
        migrations.CreateModel(
            name='TokenAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(db_index=True)),
                ('confirmed_balance',
                 models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('unconfirmed_balance',
                 models.DecimalField(db_index=True, decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('enclave_address', models.CharField(db_index=True, max_length=64, null=True)),
                ('data_iv', models.BinaryField(null=True)),
                ('enclave_data', models.BinaryField(null=True)),
                ('policy_data', models.BinaryField(null=True)),
                ('revision', models.PositiveIntegerField(db_index=True, default=0)),
                ('hsm_sig', models.BinaryField(null=True)),
                ('last_qtum_sync', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
            ],
            bases=(sys_base.hsm.model.SecureModel, models.Model),
        ),
    ]
