# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-11 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_hermes', '0002_auto_20180214_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenaccount',
            name='enclave_address',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
