# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 01:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import sys_base.fields.field_fulltext
import sys_base.hsm.model
import sys_base.profile.image


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('silo_geodata', '0001_initial'),
        ('plant_hermes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('hid', models.CharField(db_index=True, max_length=8, unique=True)),
                ('avatar_prefix', models.CharField(max_length=8, null=True)),
                ('avatar_size', models.PositiveSmallIntegerField(null=True)),
                ('avatar_set', models.BooleanField(db_index=True)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(unique=True),
                                                                    db_index=True, default=list, size=None)),
                ('dob', models.DateField(db_index=True)),
                ('gid_is', models.SmallIntegerField(choices=[(1, b'ID_MALE'), (2, b'ID_FEMALE')], db_index=True)),
                ('gid_seeking', models.SmallIntegerField(choices=[(1, b'ID_MALE'), (2, b'ID_FEMALE'), (3, b'ID_BOTH')],
                                                         db_index=True)),
                ('seeking_age_from', models.PositiveSmallIntegerField(db_index=True, default=18)),
                ('seeking_age_to', models.PositiveSmallIntegerField(db_index=True, default=88)),
                ('location_set', models.BooleanField(db_index=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40, null=True)),
                ('tagline', models.TextField(blank=True, default=b'', null=True)),
                ('bio', models.TextField(blank=True, default=b'', null=True)),
                ('name_tsv',
                 sys_base.fields.field_fulltext.VectorField(db_index=True, default=b'', editable=False, null=True,
                                                            serialize=False)),
                ('email_tsv',
                 sys_base.fields.field_fulltext.VectorField(db_index=True, default=b'', editable=False, null=True,
                                                            serialize=False)),
                ('tagline_tsv',
                 sys_base.fields.field_fulltext.VectorField(db_index=True, default=b'', editable=False, null=True,
                                                            serialize=False)),
                ('bio_tsv',
                 sys_base.fields.field_fulltext.VectorField(db_index=True, default=b'', editable=False, null=True,
                                                            serialize=False)),
                ('text_tsv',
                 sys_base.fields.field_fulltext.VectorField(db_index=True, default=b'', editable=False, null=True,
                                                            serialize=False)),
                ('hsm_sig', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(sys_base.profile.image.ProfileImage, sys_base.hsm.model.SecureModel, models.Model),
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('verified_timestamp', models.DateTimeField(db_index=True, null=True)),
                ('disabled', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('status',
                 models.SmallIntegerField(choices=[(1, b'STATUS_READY'), (2, b'STATUS_USED'), (3, b'STATUS_VOID')],
                                          db_index=True, default=1)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='email_confirmations', to='silo_user.EmailAddress')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirmations',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgot_password_requests',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.SmallIntegerField(
                    choices=[(1, b'CONTEXT_NORMAL'), (2, b'CONTEXT_GEOLOCATED'), (3, b'CONTEXT_RANDOM')],
                    db_index=True)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=5, max_digits=8)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('precision', models.SmallIntegerField(
                    choices=[(1, b'PRECISION_POINT'), (2, b'PRECISION_PLACE'), (3, b'PRECISION_ADMIN4'),
                             (4, b'PRECISION_ADMIN3'), (5, b'PRECISION_ADMIN2'), (6, b'PRECISION_ADMIN1'),
                             (7, b'PRECISION_COUNTRY')], db_index=True, null=True)),
                ('admin1',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silo_geodata.Admin1')),
                ('admin2',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silo_geodata.Admin2')),
                ('admin3',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silo_geodata.Admin3')),
                ('admin4',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silo_geodata.Admin4')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silo_geodata.Country')),
                ('place',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silo_geodata.Place')),
                ('postalcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='silo_geodata.PostalCode')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_match', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(db_index=True)),
                ('last_update', models.DateTimeField(db_index=True)),
                ('recipient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_reaction',
                                   to=settings.AUTH_USER_MODEL)),
                ('sender',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_reaction',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner',
                                       to='silo_user.Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='token_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owner',
                                       to='plant_hermes.TokenAccount'),
        ),
    ]
