# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('silo_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_account',
            field=models.PositiveIntegerField(),
        ),
    ]
