# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('silo_user', '0002_auto_20180214_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_set',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
