# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('silo_user', '0003_auto_20180214_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location_set',
        ),
    ]
