# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('silo_user', '0004_auto_20180214_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_prefix',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_set',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_account',
        ),
    ]
