# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('plant_hermes', '0002_auto_20180214_0131'),
        ('silo_user', '0005_auto_20180214_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_prefix',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_set',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_size',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner',
                                       to='silo_user.Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_set',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='token_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner',
                                       to='plant_hermes.TokenAccount'),
        ),
    ]
