# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('silo_user', '0007_auto_20180326_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gid_is',
            field=models.SmallIntegerField(choices=[(1, b'ID_MALE'), (2, b'ID_FEMALE')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gid_seeking',
            field=models.SmallIntegerField(choices=[(1, b'ID_MALE'), (2, b'ID_FEMALE'), (3, b'ID_BOTH')], db_index=True,
                                           null=True),
        ),
    ]
