# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-22 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('silo_user', '0008_auto_20180518_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gid_is',
            field=models.SmallIntegerField(choices=[(1, b'ID_MALE'), (2, b'ID_FEMALE'), (3, b'ID_OTHER')],
                                           db_index=True, null=True),
        ),
    ]
