# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-23 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('silo_user', '0009_auto_20180522_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
