# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('silo_user', '0010_auto_20180523_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.SmallIntegerField(
                choices=[(1, b'INCOMPLETE'), (2, b'ACTIVE'), (3, b'DISABLED'), (4, b'DELETED')], db_index=True,
                default=1),
        ),
    ]
