# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-12 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('silo_user', '0011_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(
                    choices=[(1, b'INCOMPLETE'), (2, b'ACTIVE'), (3, b'DISABLED'), (4, b'DELETED')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reason1', models.BooleanField()),
                ('reason2', models.BooleanField()),
                ('reason3', models.BooleanField()),
                ('reason4', models.BooleanField()),
                ('reason5', models.BooleanField()),
                ('comment', models.CharField(max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
