# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo_user', '0012_exitsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'STATUS_READY'), (2, 'STATUS_USED'), (3, 'STATUS_VOID')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='exitsurvey',
            name='state',
            field=models.SmallIntegerField(choices=[(1, 'INCOMPLETE'), (2, 'ACTIVE'), (3, 'DISABLED'), (4, 'DELETED')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='context',
            field=models.SmallIntegerField(choices=[(1, 'CONTEXT_NORMAL'), (2, 'CONTEXT_GEOLOCATED'), (3, 'CONTEXT_RANDOM')], db_index=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='precision',
            field=models.SmallIntegerField(choices=[(1, 'PRECISION_POINT'), (2, 'PRECISION_PLACE'), (3, 'PRECISION_ADMIN4'), (4, 'PRECISION_ADMIN3'), (5, 'PRECISION_ADMIN2'), (6, 'PRECISION_ADMIN1'), (7, 'PRECISION_COUNTRY')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gid_is',
            field=models.SmallIntegerField(choices=[(1, 'ID_MALE'), (2, 'ID_FEMALE'), (3, 'ID_OTHER')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gid_seeking',
            field=models.SmallIntegerField(choices=[(1, 'ID_MALE'), (2, 'ID_FEMALE'), (3, 'ID_BOTH')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='seeking_age_to',
            field=models.PositiveSmallIntegerField(db_index=True, default=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.SmallIntegerField(choices=[(1, 'INCOMPLETE'), (2, 'ACTIVE'), (3, 'DISABLED'), (4, 'DELETED')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='tagline',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
