# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-04 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silo_user', '0013_auto_20180628_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hsm_sig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='silo_user.Location'),
        ),
    ]
