# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-11 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silo_user', '0014_auto_20180704_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='plant_hermes.TokenAccount'),
        ),
    ]
