# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo_message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='bid_status',
            field=models.SmallIntegerField(choices=[(1, 'BID_WINNING'), (2, 'BID_LOSING'), (3, 'BID_WON'), (4, 'BID_LOST'), (5, 'BID_ACCEPTED'), (6, 'BID_TIMEOUT')], db_index=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='recipient_status',
            field=models.SmallIntegerField(choices=[(1, 'STATUS_PENDING'), (2, 'STATUS_CURRENT')], db_index=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='sender_status',
            field=models.SmallIntegerField(choices=[(1, 'STATUS_PENDING'), (2, 'STATUS_CURRENT')], db_index=True),
        ),
        migrations.AlterField(
            model_name='introsettings',
            name='max_daily_intros',
            field=models.PositiveSmallIntegerField(db_index=True, default=4),
        ),
    ]
