# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-17 11:51
from __future__ import unicode_literals

from django.db import migrations, models
from silo_message.message import Message, MessageType


def apply_default(apps, schema):
    for message in Message.objects.all():
        message.type = MessageType.STANDARD
        message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('silo_message', '0002_auto_20180628_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default=b'STANDARD', max_length=8),
        ),
        migrations.RunPython(apply_default),
    ]
