# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-20 10:03
from __future__ import unicode_literals

from django.db import migrations, models

from silo_message.message import MessageType
from silo_message.conversation import Conversation


def apply_default(apps, schema):
    for conversation in Conversation.objects.all():
        conversation.subject_type = MessageType.STANDARD
        conversation.save()

class Migration(migrations.Migration):


    dependencies = [
        ('silo_message', '0003_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='subject_type',
            field=models.CharField(default=b'STANDARD', max_length=8),
        ),
        migrations.RunPython(apply_default),
    ]
