# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import sys_base.fields.field_json
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('worker_id', models.SmallIntegerField(db_index=True)),
                ('queued', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.SmallIntegerField(
                    choices=[(1, b'TYPE_AUCTION_ACCEPT'), (2, b'TYPE_AUCTION_EXPIRED'), (3, b'TYPE_AUCTION_LOSING'),
                             (4, b'TYPE_AUCTION_LOST'), (5, b'TYPE_AUCTION_WON'), (10, b'TYPE_HELIOS_SIGNUP'),
                             (11, b'TYPE_HELIOS_CHANGE_EMAIL'), (12, b'TYPE_HELIOS_FORGOT_PASS'),
                             (20, b'TYPE_MESSAGE_NEW')], db_index=True)),
                ('data', sys_base.fields.field_json.JSONField(default=b'', editable=False, null=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SentNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('notice_type', models.SmallIntegerField(
                    choices=[(1, b'TYPE_AUCTION_ACCEPT'), (2, b'TYPE_AUCTION_EXPIRED'), (3, b'TYPE_AUCTION_LOSING'),
                             (4, b'TYPE_AUCTION_LOST'), (5, b'TYPE_AUCTION_WON'), (10, b'TYPE_HELIOS_SIGNUP'),
                             (11, b'TYPE_HELIOS_CHANGE_EMAIL'), (12, b'TYPE_HELIOS_FORGOT_PASS'),
                             (20, b'TYPE_MESSAGE_NEW')], db_index=True)),
                ('queued', models.DateTimeField(db_index=True)),
                ('processed', models.DateTimeField(db_index=True)),
                ('data', sys_base.fields.field_json.JSONField(default=b'', editable=False, null=True, serialize=False)),
                ('api_response',
                 sys_base.fields.field_json.JSONField(default=b'', editable=False, null=True, serialize=False)),
                ('status', models.SmallIntegerField(
                    choices=[(1, b'STATUS_EOS_SENT'), (2, b'STATUS_EOS_TEST'), (3, b'STATUS_EOS_DROP'),
                             (4, b'STATUS_API_ERROR'), (5, b'STATUS_EOS_FAIL')], db_index=True)),
                ('guid', models.UUIDField(db_index=True)),
            ],
        ),
    ]
