# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_eos', '0002_auto_20180214_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'TYPE_AUCTION_ACCEPT'), (2, 'TYPE_AUCTION_EXPIRED'), (3, 'TYPE_AUCTION_LOSING'), (4, 'TYPE_AUCTION_LOST'), (5, 'TYPE_AUCTION_WON'), (10, 'TYPE_HELIOS_SIGNUP'), (11, 'TYPE_HELIOS_CHANGE_EMAIL'), (12, 'TYPE_HELIOS_FORGOT_PASS'), (20, 'TYPE_MESSAGE_NEW')], db_index=True),
        ),
        migrations.AlterField(
            model_name='sentnotice',
            name='notice_type',
            field=models.SmallIntegerField(choices=[(1, 'TYPE_AUCTION_ACCEPT'), (2, 'TYPE_AUCTION_EXPIRED'), (3, 'TYPE_AUCTION_LOSING'), (4, 'TYPE_AUCTION_LOST'), (5, 'TYPE_AUCTION_WON'), (10, 'TYPE_HELIOS_SIGNUP'), (11, 'TYPE_HELIOS_CHANGE_EMAIL'), (12, 'TYPE_HELIOS_FORGOT_PASS'), (20, 'TYPE_MESSAGE_NEW')], db_index=True),
        ),
        migrations.AlterField(
            model_name='sentnotice',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'STATUS_EOS_SENT'), (2, 'STATUS_EOS_TEST'), (3, 'STATUS_EOS_DROP'), (4, 'STATUS_API_ERROR'), (5, 'STATUS_EOS_FAIL')], db_index=True),
        ),
    ]
