# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo_asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stashedasset',
            name='state',
            field=models.CharField(choices=[('NONE', 'STATE_NONE'), ('WAITING', 'STATE_WAITING'), ('STARTED', 'STATE_STARTED'), ('DONE', 'STATE_DONE'), ('FAILED', 'STATE_FAILED')], db_index=True, max_length=16),
        ),
    ]
